-- Import des produits depuis Notion (81 produits)
-- À coller dans Supabase > SQL Editor, APRÈS avoir exécuté schema.sql et créé ton compte.
-- Les produits sont rattachés au premier (et seul) compte utilisateur.

do $$
declare uid uuid := (select id from auth.users order by created_at limit 1);
begin
  if uid is null then
    raise exception 'Aucun utilisateur : crée d''abord ton compte dans Authentication > Users';
  end if;

  insert into public.products (user_id, brand, product, name, color, is_pr)
  select uid, v.* from (values
  ('WYCON Cosmetics', 'crayon', 'Intense eye pencil', 'Metallic purple', false),
  ('WYCON Cosmetics', 'far liquide', 'Eyeconic liquid tint', '202', false),
  ('WYCON Cosmetics', 'far à paupière', 'Visionary eyeshadow', '11', false),
  ('WYCON Cosmetics', 'crayon', 'Wonderproof eye pencil', 'Extreme black', false),
  ('Lethal Cosmetics', 'palette', 'Spongebob', null, false),
  ('Glitch Beauty', 'palette', 'Prolog', null, false),
  ('Jolie Beauty', 'palette', 'Vampyrism', null, false),
  ('Jolie Beauty', 'palette', 'Spellbound', null, false),
  ('Tony Moly', 'palette', 'Super Beam', 'edition spéciale, Moschino', false),
  ('Beauty Bay', 'palette', 'Matte', null, false),
  ('Cosmic Beauty', 'palette', 'Undergrowth', null, false),
  ('Huda Beauty', 'palette', 'Emerald Obsessions', null, false),
  ('KIKO', 'palette', 'Bright duo', null, false),
  ('Nyx', 'blush', 'Fat Cheeks', 'FB02', false),
  ('Tarte', 'blush', 'Amazonian clay 12-hour', 'paaarty', false),
  ('Nyx', 'mascara', 'Worth the hype', 'black', false),
  ('Glisten Cosmetics', 'mascara', 'Spectra Lash', 'teal', false),
  ('Glisten Cosmetics', 'mascara', 'Spectra Lash', 'soybean', false),
  ('Glisten Cosmetics', 'mascara', 'Spectra Lash', 'orange', false),
  ('Glisten Cosmetics', 'mascara', 'Spectra Lash', 'auburn', false),
  ('Glisten Cosmetics', 'mascara', 'Spectra Lash', 'green', false),
  ('Glisten Cosmetics', 'mascara', 'Spectra Lash', 'candy floss', false),
  ('Essence', 'mascara', 'i love extreme', 'blue', false),
  ('HEMA', 'mascara', 'volume', 'blue', false),
  ('Nyx', 'base', 'Shadow & liner primer', null, false),
  ('Nyx', 'concealer', 'Pro fix stick', 'pink', false),
  ('Huda Beauty', 'concealer', 'Fauxfilter', 'honey', false),
  ('Nyx', 'rouge à lèvres', 'Soft matte lip cream', 'Toulouse', false),
  ('KIKO', 'poudre', 'Matte loose powder', 'Apricot crush', false),
  ('KIKO', 'poudre', 'Matte fusion', null, false),
  ('3INA', 'eyeliner', 'The color pen eyeliner', '830', false),
  ('3INA', 'eyeliner', 'The color pen eyeliner', '759', false),
  ('Nyx', 'eyeliner', 'Epic Wear', 'red', false),
  ('Nyx', 'eyeliner', 'Epic Wear', 'teal metal', false),
  ('Nyx', 'eyeliner', 'Epic Wear', 'silver metal', false),
  ('Nyx', 'eyeliner', 'Epic inky stix', 'on-lime', false),
  ('Nyx', 'eyeliner', 'Epic inky stix', 'violet volt', false),
  ('Nyx', 'eyeliner', 'Epic inky stix', 'silver shock', false),
  ('Nyx', 'eyeliner', 'Epic ink liner', 'black', false),
  ('Glisten Cosmetics', 'eyeliner', 'Wet liner', 'peach', false),
  ('Glisten Cosmetics', 'eyeliner', 'Wet liner', 'strawberry', false),
  ('Glisten Cosmetics', 'eyeliner', 'Wet liner', 'cola', false),
  ('Glisten Cosmetics', 'eyeliner', 'Wet liner', 'bubblegum', false),
  ('Glisten Cosmetics', 'eyeliner', 'Wet liner', 'plum', false),
  ('Glisten Cosmetics', 'eyeliner', 'Wet liner', 'aubergine', false),
  ('Glisten Cosmetics', 'eyeliner', 'Wet liner', 'mint', false),
  ('Glisten Cosmetics', 'eyeliner', 'Wet liner', 'vanilla', false),
  ('Glisten Cosmetics', 'eyeliner', 'Wet liner', 'milk', false),
  ('Glisten Cosmetics', 'eyeliner', 'Wet liner', 'moonlight', false),
  ('Glisten Cosmetics', 'eyeliner', 'Wet liner', 'blueberry', false),
  ('Glisten Cosmetics', 'eyeliner', 'Wet liner', 'grape', false),
  ('MTCosmetics', 'eyeliner', 'LumiLiner', '19 belle', false),
  ('MTCosmetics', 'eyeliner', 'LumiLiner', '7 rapunzel', false),
  ('MTCosmetics', 'eyeliner', 'LumiLiner', '1 cinderella', false),
  ('Glisten Cosmetics', 'eyeliner', 'Chroma flik', 'frosting', false),
  ('Glisten Cosmetics', 'eyeliner', 'Chroma flik', 'cyclops', false),
  ('Glisten Cosmetics', 'eyeliner', 'Chroma flik', 'medusa', false),
  ('Lethal Cosmetics', 'eyeliner', 'Zuko', 'multichrome', false),
  ('Lethal Cosmetics', 'eyeliner', 'Zuko', 'matte', false),
  ('Maybelline', 'crayon', 'TattooLiner', 'artic skies', false),
  ('Maybelline', 'crayon', 'TattooLiner', 'orange flash', false),
  ('Maybelline', 'crayon', 'TattooLiner', 'citus charge', false),
  ('Maybelline', 'crayon', 'TattooLiner', 'ultra pink', false),
  ('Maybelline', 'crayon', 'TattooLiner', 'burgundy break', false),
  ('Glisten Cosmetics', 'crayon', 'Chroma pencil', 'intergalatic', false),
  ('Glisten Cosmetics', 'crayon', 'Chroma pencil', 'bora bora', false),
  ('L''Oréal', 'crayon', 'Khôl nature', 'vert', false),
  ('L''Oréal', 'crayon', 'Khôl naturel', 'blanc', false),
  ('Sephora', 'crayon', '12h colorful special effects', 'celestial blue', false),
  ('Sephora', 'crayon', '12h colorful special effects', 'green aurora', false),
  ('Langanni', 'far liquide', 'Liquid glitter eyeshadow', 'wonder', false),
  ('Langanni', 'far liquide', 'Liquid glitter eyeshadow', 'ember', false),
  ('Langanni', 'far liquide', 'Liquid glitter eyeshadow', 'peacock', false),
  ('Nyx', 'far liquide', 'glow shots', 'feelin’ grape', false),
  ('Glisten Cosmetics', 'far liquide', 'Chroma magic', 'voodoo', false),
  ('Sephora', 'far à paupière', 'Colorful', 'unicorn dust', false),
  ('MTCosmetics', 'far à paupière', 'Multichrome highlighter', 'gummy bear', false),
  ('MTCosmetics', 'far à paupière', 'Multichrome highlighter', 'bubble swirl', false),
  ('MTCosmetics', 'far à paupière', 'Multichrome highlighter', 'taffy drizzle', false),
  ('Fenty Beauty', 'gloss', 'Gloss oil', 'Caitlyn', false),
  ('Fenty Beauty', 'gloss', 'Gloss oil bomb', 'Miss Jellyfish', false)
  ) as v(brand, product, name, color, is_pr);
end $$;
